name: Packer Build

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:
  integration-test:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --upgrade --no-cache-dir

      - name: Run Integration Tests
        env:
          TESTING: "True"
        run: |
          pytest --verbose

  build-custom-image:
    name: Build Custom Image in AWS
    needs: integration-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Verify AWS Credentials
        run: aws sts get-caller-identity

      - name: Install Packer
        uses: hashicorp/setup-packer@v2
        with:
          version: latest

      - name: Enable Packer Logging
        run: |
          export PACKER_LOG=1
          export PACKER_LOG_PATH="packer.log"

      - name: Build Image with Packer in AWS
        run: |
          packer init packer/webapp.pkr.hcl
          packer build -var "db_password=${{ secrets.DB_PASSWORD }}" packer/webapp.pkr.hcl

      - name: Upload Packer Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: packer-logs
          path: packer.log

      - name: Configure Systemd Service
        run: |
          sudo systemctl daemon-reload
          sudo systemctl enable csye6225.service